const ROLES = {
  ADMIN: "Admin",
  MANAGER: "Manager",
  EMPLOYEE: "Employee",
  CLIENT: "Client",
  CLIENT_VIEWER: "Client-Viewer",
};

const LOGIN_RESPONSES = {
  admin: {
    user: {
      id: "ac510b2dd0e311f088c200155daedf50",
      email: "admin@example.com",
      name: "Admin User",
      role: "Admin",
      modules: [
        { moduleId: "6a2ef6584bce3025", name: "Dashboard", access: "full", path: "/admin/dashboard" },
        { moduleId: "c22786746f3072d6", name: "User Management", access: "full", path: "/admin/users" },
        { moduleId: "45bb31719857f4b3", name: "Clients", access: "full", path: "/admin/clients" },
        { moduleId: "39d338c671d58e03", name: "Departments", access: "full", path: "/admin/departments" },
        { moduleId: "43a793d6fea2f370", name: "Tasks", access: "full", path: "/admin/tasks" },
        { moduleId: "793756e1d0997601", name: "Projects", access: "full", path: "/admin/projects" },
        { moduleId: "c826110014caa10e", name: "Workflow (Project & Task Flow)", access: "full", path: "/admin/workflow" },
        { moduleId: "8bde69403e370854", name: "Notifications", access: "full", path: "/admin/notifications" },
        { moduleId: "63c9ab2ec626ee63", name: "Reports & Analytics", access: "full", path: "/admin/reports" },
        { moduleId: "45fb8742255ce2f7", name: "Document & File Management", access: "full", path: "/admin/documents" },
        { moduleId: "a814d9abf691c2f9", name: "Chat / Real-Time Collaboration", access: "full", path: "/admin/chat" },
        { moduleId: "b32e298a4d889334", name: "Approval Workflows", access: "full", path: "/admin/approvals" },
        { moduleId: "435f640487c33b57", name: "Settings & Master Configuration", access: "full", path: "/admin/settings" },
      ],
      sidebar: [
        { id: "dashboard", label: "Dashboard", icon: "dashboard", path: "/admin/dashboard" },
        {
          id: "clients",
          label: "Clients",
          icon: "business",
          path: "/admin/clients",
          children: [
            { id: "clients-list", label: "Client List", path: "/admin/clients" },
            { id: "clients-create", label: "Add Client", path: "/admin/clients/create" },
          ],
        },
        { id: "users", label: "User Management", icon: "people", path: "/admin/users" },
        { id: "departments", label: "Departments", icon: "domain", path: "/admin/departments" },
        { id: "tasks", label: "Tasks", icon: "task", path: "/admin/tasks" },
        { id: "projects", label: "Projects", icon: "project", path: "/admin/projects" },
        { id: "analytics", label: "Analytics", icon: "analytics", path: "/admin/analytics" },
        { id: "reports", label: "Reports", icon: "report", path: "/admin/reports" },
        { id: "settings", label: "Settings", icon: "settings", path: "/admin/settings" },
      ],
      phone: "9513035255",
    },
    metrics: {
      totalUsers: 4,
      totalClients: 0,
      totalTasks: 0,
      totalProjects: 0,
      role: "Admin",
      accessLevel: "Full Access",
    },
    resources: {
      canViewAllClients: true,
      canCreateClients: true,
      canManageUsers: true,
      canViewAnalytics: true,
      canManageDepartments: true,
      canSeeAllTasks: true,
      canCreateProjects: true,
      canApprove: true,
      features: ["Clients", "Users", "Tasks", "Projects", "Dashboard", "Analytics", "Reports", "Settings"],
    },
  },
  manager: {
    user: {
      id: "managerpub5678",
      email: "manager@example.com",
      name: "Manager Name",
      role: "Manager",
      modules: [
        { moduleId: "6a2ef6584bce3025", name: "Dashboard", access: "full", path: "/manager/dashboard" },
        { moduleId: "45bb31719857f4b3", name: "Clients", access: "full", path: "/manager/clients" },
        { moduleId: "43a793d6fea2f370", name: "Tasks", access: "full", path: "/manager/tasks" },
        { moduleId: "793756e1d0997601", name: "Projects", access: "full", path: "/manager/projects" },
        { moduleId: "c826110014caa10e", name: "Workflow (Project & Task Flow)", access: "full", path: "/manager/workflow" },
        { moduleId: "8bde69403e370854", name: "Notifications", access: "read", path: "/manager/notifications" },
        { moduleId: "63c9ab2ec626ee63", name: "Reports & Analytics", access: "full", path: "/manager/reports" },
        { moduleId: "45fb8742255ce2f7", name: "Document & File Management", access: "full", path: "/manager/documents" },
      ],
      sidebar: [
        { id: "dashboard", label: "Dashboard", icon: "dashboard", path: "/manager/dashboard" },
        {
          id: "clients",
          label: "Clients",
          icon: "business",
          path: "/manager/clients",
          children: [
            { id: "clients-list", label: "Client List", path: "/manager/clients" },
            { id: "clients-create", label: "Add Client", path: "/manager/clients/create" },
          ],
        },
        { id: "tasks", label: "Tasks", icon: "task", path: "/manager/tasks" },
        { id: "projects", label: "Projects", icon: "project", path: "/manager/projects" },
        { id: "reports", label: "Reports", icon: "report", path: "/manager/reports" },
      ],
      phone: "9513035256",
    },
    metrics: {
      totalUsers: 0,
      totalClients: 12,
      totalTasks: 45,
      totalProjects: 8,
      role: "Manager",
      accessLevel: "Manager Access",
    },
    resources: {
      canViewAllClients: true,
      canCreateClients: true,
      canManageUsers: false,
      canViewAnalytics: true,
      canCreateProjects: true,
      canApprove: true,
      features: ["Clients", "Tasks", "Projects", "Dashboard", "Reports"],
    },
  },
  employee: {
    user: {
      id: "d96acaea378d5fe5",
      email: "employee@example.com",
      name: "Employee User",
      role: "Employee",
      modules: [
        { moduleId: "6a2ef6584bce3025", name: "Dashboard", access: "read", path: "/employee/dashboard" },
        { moduleId: "43a793d6fea2f370", name: "Tasks", access: "read", path: "/employee/tasks" },
        { moduleId: "8bde69403e370854", name: "Notifications", access: "read", path: "/employee/notifications" },
        { moduleId: "45fb8742255ce2f7", name: "Document & File Management", access: "read", path: "/employee/documents" },
      ],
      sidebar: [
        { id: "dashboard", label: "Dashboard", icon: "dashboard", path: "/employee/dashboard" },
        { id: "my-tasks", label: "My Tasks", icon: "task", path: "/employee/tasks" },
      ],
      phone: "9513035257",
      title: "Software Developer",
      department: "Engineering",
    },
    metrics: {
      totalUsers: 0,
      totalClients: 0,
      totalTasks: 8,
      totalProjects: 0,
      role: "Employee",
      accessLevel: "Employee Access",
    },
    resources: {
      canViewAllClients: false,
      canCreateClients: false,
      canManageUsers: false,
      canViewAnalytics: false,
      canCreateProjects: false,
      canApprove: false,
      features: ["Tasks", "Dashboard"],
    },
  },
  clientviewer: {
    user: {
      id: "clientpub999",
      email: "client@example.com",
      name: "Client Name",
      role: "Client-Viewer",
      modules: [
        { moduleId: "6a2ef6584bce3025", name: "Dashboard", access: "read", path: "/client/dashboard" },
        { moduleId: "793756e1d0997601", name: "Projects", access: "read", path: "/client/projects" },
        { moduleId: "43a793d6fea2f370", name: "Tasks", access: "read", path: "/client/tasks" },
        { moduleId: "63c9ab2ec626ee63", name: "Reports & Analytics", access: "read", path: "/client/reports" },
        { moduleId: "45fb8742255ce2f7", name: "Document & File Management", access: "read", path: "/client/documents" },
      ],
      sidebar: [
        { id: "dashboard", label: "Dashboard", icon: "dashboard", path: "/client/dashboard" },
        { id: "projects", label: "Projects", icon: "project", path: "/client/projects" },
        { id: "tasks", label: "Tasks", icon: "task", path: "/client/tasks" },
        { id: "reports", label: "Reports", icon: "report", path: "/client/reports" },
      ],
      clientId: 55,
      clientName: "nikitha kondareddy",
      company: "ABC Corp",
    },
    metrics: {
      totalUsers: 0,
      totalClients: 1,
      totalTasks: 5,
      totalProjects: 2,
      role: "Client-Viewer",
      accessLevel: "Read Only",
    },
    resources: {
      canViewAllClients: false,
      canCreateClients: false,
      features: ["Projects", "Tasks", "Dashboard", "Reports"],
    },
  },
  client: {
    user: {
      id: "clientpub888",
      email: "client@company.com",
      name: "Client Company",
      role: "Client",
      modules: [
        { moduleId: "6a2ef6584bce3025", name: "Dashboard", access: "read", path: "/client/dashboard" },
        { moduleId: "793756e1d0997601", name: "Projects", access: "read", path: "/client/projects" },
        { moduleId: "43a793d6fea2f370", name: "Tasks", access: "read", path: "/client/tasks" },
        { moduleId: "45fb8742255ce2f7", name: "Document & File Management", access: "read", path: "/client/documents" },
      ],
      sidebar: [
        { id: "dashboard", label: "Dashboard", icon: "dashboard", path: "/client/dashboard" },
        { id: "projects", label: "Projects", icon: "project", path: "/client/projects" },
        { id: "tasks", label: "Tasks", icon: "task", path: "/client/tasks" },
      ],
      company: "XYZ Industries",
      industry: "Technology",
    },
    metrics: {
      totalUsers: 0,
      totalClients: 1,
      totalTasks: 12,
      totalProjects: 3,
      role: "Client",
      accessLevel: "Client Access",
    },
    resources: {
      canViewAllClients: false,
      canCreateClients: false,
      canApprove: false,
      features: ["Projects", "Tasks", "Dashboard"],
    },
  },
};

const normalizeRoleKey = (role) => (role || "").toString().toLowerCase().replace(/\s|-/g, "");

const getLoginResponseForRole = (role) => LOGIN_RESPONSES[normalizeRoleKey(role)] || null;
const getFallbackModules = (role) => getLoginResponseForRole(role)?.user?.modules || [];
const getFallbackSidebar = (role) => getLoginResponseForRole(role)?.user?.sidebar || [];

export {
  ROLES,
  LOGIN_RESPONSES,
  getLoginResponseForRole,
  getFallbackModules,
  getFallbackSidebar,
};
